### ISSUE TITLE
How to choose sim carrier from dual sim card

### ISSUE THREAD

**Issue by rupamking1** [vkammerer/ussd_service#10]
How to choose sim carrier from dual sim card

**Comment by rupamking1** [comment]
why you close my issue

**Comment by rupamking1** [comment]
How to choose sim carrier from dual sim card

**Comment by yeab-dev** [comment]
why are you closing the issue @vkammerer please tell us how to choose sim carrier from dual sim card

**Comment by hanumanjiblog** [comment]
yes why
