### ISSUE TITLE
Build APK throw error 

### ISSUE THREAD

**Issue by pierratono** [vkammerer/ussd_service#13]
When I run this `flutter build apk` I am getting this error and my Android module is using androidx with kotlin

❯ flutter build apk

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Note: /Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.1.0+2/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processReleaseResources'.               
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/pierratono/Dev/Works/shmyself/ussd_automator/android/app/src/main/AndroidManifest.xml:7:8-69: AAPT: error: unexpected element <uses-permission> found in <manifest><application>.
                                                                        
     /Users/pierratono/Dev/Works/shmyself/ussd_automator/android/app/src/main/AndroidManifest.xml:8:8-78: AAPT: error: unexpected element <uses-permission> found in <manifest><application>.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 36s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     109.5s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try
using Jetifier to solve the incompatibility.
Building plugin permission_handler...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                 2,848ms
✓ Built build/app/outputs/repo.
Building plugin sim_data...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                 2,796ms

/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:10: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:11: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;
                            ^
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:36: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
                                  ^
  symbol:   class NonNull
  location: class SimDataPlugin
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:53: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
                                    ^
  symbol:   class NonNull
  location: class SimDataPlugin
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:60: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                            ^
  symbol:   class NonNull
  location: class SimDataPlugin
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:60: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                                                      ^
  symbol:   class NonNull
  location: class SimDataPlugin
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:120: error: cannot find symbol
    ActivityCompat.requestPermissions(this.activity, perm, 0);
    ^
  symbol:   variable ActivityCompat
  location: class SimDataPlugin
/Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java:124: error: cannot find symbol
    return PackageManager.PERMISSION_GRANTED == ContextCompat
                                                ^
  symbol:   variable ContextCompat
  location: class SimDataPlugin
Note: /Users/pierratono/development/flutter/.pub-cache/hosted/pub.dartlang.org/sim_data-0.0.1+2/android/src/main/java/com/vincentkammerer/sim_data/SimDataPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin sim_data could not be built due to the issue above.

**Comment by vkammerer** [comment]
It looks like you need to migrate your project to AndroidX: https://developer.android.com/jetpack/androidx/migrate
