### ISSUE TITLE
USSD call spawns popup menu

### ISSUE THREAD

**Issue by CallumDowling** [vkammerer/ussd_service#14]
Hi, 
I am using the example on this repo, it dials the ussd code, but brings up the ussd menu, and the callbacks don't register (i.e. RequestState of the call doesn't actually change until timeout occurs, and I can't print the output of the ussd response).

Is there are way/guide to use your package, but have the ussd call run completely in the background?

Using android version 9.

**Comment by vkammerer** [comment]
Hello, it is hard to help you without without more information. I'm surprised that using `ussd_service` could trigger any sort of popup. Do you mind posting more details, including code and screenshots?

**Comment by luismykun** [comment]
hello...have some one tried this https://github.com/romellfudi/VoIpUSSD ?
im new on it and i dont know how to integrate ir with flutter :(

**Comment by CallumDowling** [comment]
> hello...have some one tried this https://github.com/romellfudi/VoIpUSSD ? im new on it and i dont know how to integrate ir with flutter :(

From the gif, that looks awful, still pops up with ussd calls and requires the user to delve into the settings to change accessibility setting. Something that maybe 20% of my users would be competent enough to do.

@vkammerer 
I gave you all the information I though was necessary, but if you want to see what I mean by popping up ussd menu, look at the link @luismykun just posted. I want the ussd calls to be run completely in the background, newer version of android have TelephonyManager.sendUssdRequest(), this ostensibly does what I am looking for, but I can't get it to work (I have tried ussd phase 1 and 2) and get -1 return every time. If you could get this to work with your flutter project I would be very happy.

**Comment by vkammerer** [comment]
@CallumDowling Could you please post a screenshot of the behaviour you are seeing?

**Comment by CallumDowling** [comment]
@vkammerer 
Hi, I don't really have the app set up right now, it shows a menu like this then the dialer pops up, exactly as https://github.com/romellfudi/VoIpUSSD in the first gif - it shows "ussd code running..." then briefly pops up with dialer, then populates the app with accessibility data. I want to skip all the middle steps, dial a ussd completely in the background, then handle data myself.

See this image for the popup.
![image](https://user-images.githubusercontent.com/22888330/135807264-55b32691-50d4-4201-9932-df80f94fc8d2.png)

**Comment by vkammerer** [comment]
@CallumDowling without the code that is triggering the popup, I can't help you. Please include the code that is triggering the popup, and a screenshot of the UI produced by that code.
