### ISSUE TITLE
Version of Android supported by the plugin

### ISSUE THREAD

**Issue by kouroumapaul** [vkammerer/ussd_service#16]
**Hello**
What is the supported Android version for this plugin ?
I'm trying to execute the UssdService.makeRequest method but i didn't get any response on Android 8.

**Comment by devmuaz** [comment]
@kouroumapaul I believe Android 8 is supported since the minSdk is set to 26

**Comment by vkammerer** [comment]
Android 8 is supported indeed, since the API was introduced with the SDK version 26. Your issue probably came from another factor
