### ISSUE TITLE
No implementation found for method (flutter)

### ISSUE THREAD

**Issue by Smueez** [vkammerer/ussd_service#17]
`makeMyRequest() async {
    int subscriptionId = -1; // sim card subscription ID
    String code = "*778#"; // ussd code payload
    try {
      String ussdResponseMessage = await UssdService.makeRequest(
        subscriptionId,
        code// timeout (optional) - default is 10 seconds
      );
      print("succes! message: $ussdResponseMessage");
    } catch(e) {
      // debugPrint("error! code: ${e.code} - message: ${e.message}");
      print('make my reqest error $e');
    }
  }`
**Error**: make my reqest error MissingPluginException(No implementation found for method makeRequest on channel com.vincentkammerer.ussd_service/plugin_channel)
Can anyone look into this issue? thanks

**Comment by vkammerer** [comment]
It looks like you haven't installed the plugin properly, so this issue is not related to the plugin directly, but to how you run it.
