### ISSUE TITLE
Support for SDKs < 26

### ISSUE THREAD

**Issue by DonnC** [vkammerer/ussd_service#2]
Great package but after creating a default flutter app and adding this package to pubsec it shows that minSdk must bt >= 26 
Is there a way to support for lower SDKs or android version.

**Comment by LSambo02** [comment]
As the support library was only added for Sdk 26, I guess it can't be done [TelephonyManager.UssdResponseCallback](https://developer.android.com/reference/android/telephony/TelephonyManager.UssdResponseCallback). What can be done is to edit the 
gradle.build [app] `minSdkVersion 26`

**Comment by DonnC** [comment]
I tried changing sdk version in the gradle file and the app crushed when i tried requesting
Thanks for the link i have seen where its supported as you have mentioned 👏

**Comment by DonnC** [comment]
Closing!

**Comment by LSambo02** [comment]
Try using 0.0.4+1 previous version of the plugin
