### ISSUE TITLE
Getting Platform Exception

### ISSUE THREAD

**Issue by K0M4L** [vkammerer/ussd_service#20]
Error! Code: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null) - Message PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)

sendUssd works fine but sendAdvancedUssd is giving above issue. I'm running on android version 12

**Comment by vkammerer** [comment]
I think you are posting this issue in the wrong repository. `sendAdvancedUssd` exists only in https://github.com/EddieKamau/ussd_advanced

**Comment by K0M4L** [comment]
error! code: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null) - message: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null, null)
I'm getting the same error when trying with ussd_service package. Can you tell me possible fix.
