### ISSUE TITLE
want to establish a phone call 

### ISSUE THREAD

**Issue by hssn-hassnain** [vkammerer/ussd_service#5]
Hi its a impressive work on the plugin i am making a phone calling app so i see in this plugin that other than ussd it is is also calling. i want to establish the call through my app instead of opening phone dialer. In order to do so what changes i have to make if i use this plugin. can u help me with this. this will be a great help for me. thanks

**Comment by vkammerer** [comment]
Sorry but this plugin doesn't intercept phone calls. The `CALL_PHONE` permission is required only to execute the USSD request.
