### ISSUE TITLE
When are you supporting iOS?

### ISSUE THREAD

**Issue by nizigama** [vkammerer/ussd_service#6]
This plugin looks promising, but i just wanted to know if there is any future plan of support iOS also

**Comment by vkammerer** [comment]
Hello,

if iOS launches a silent way of making USSD requests, it could be integrated into this plugin, but for now there is no equivalent. This plugin is currently only a wrapper around Android's [sendUssdRequest](https://developer.android.com/reference/android/telephony/TelephonyManager.html#sendUssdRequest(java.lang.String,%20android.telephony.TelephonyManager.UssdResponseCallback,%20android.os.Handler))
