### ISSUE TITLE
which version has below minsdk21?

### ISSUE THREAD

**Issue by iwacu** [vkammerer/ussd_service#8]
Hello , which version can we use which is has minsdk_version below 21?

**Comment by vkammerer** [comment]
As can be seen on Android's [sendUssdRequest documentation page](https://developer.android.com/reference/android/telephony/TelephonyManager.html#sendUssdRequest(java.lang.String,%20android.telephony.TelephonyManager.UssdResponseCallback,%20android.os.Handler)) , the method was added in API Level 26 so no version below it will be supported.

**Comment by iwacu** [comment]
ok
