### ISSUE TITLE
Ussd breaks for normal calls

### ISSUE THREAD

**Issue by LSambo02** [vkammerer/ussd_service#9]
Whenever i use a ussd code like `*151#` it throws `[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: PlatformException(ussd_plugin_ussd_execution_failure, USSD_RETURN_FAILURE, null)` it only seems to work with codes similar with `*#151#` which in my specific case aren't applicable. Any help to have both ways working at least?

**Comment by vkammerer** [comment]
If you are receiving the failure message correctly from the Android side, it means that the behaviour you are reporting concerns Android's implementation of `sendUssdRequest`.
Please report this to the Android team.
